__package__ = "translate.readers"
__all__ = ["data_provider", "iterators", "utils", "sequence_alignment", "tokenizers", "datasets"]
__author__ = "Hassan S. Shavarani"
__copyright__ = "Copyright 2019, SFUTranslate Project"
__credits__ = ["Hassan S. Shavarani"]
__license__ = "GNU GPL 3"
__version__ = "1.0"
__maintainer__ = "Hassan S. Shavarani"
__email__ = "sshavara@sfu.ca"
__status__ = "Production"
