__package__ = "translate.learning.modules.transformer"
__all__ = ["attention", "decoder", "encoder", "transformer", "utils"]
__author__ = "Hassan S. Shavarani"
__copyright__ = "Copyright 2018, SFUTranslate Project"
__credits__ = ["Hassan S. Shavarani"]
__license__ = "MIT"
__version__ = "0.1"
__maintainer__ = "Hassan S. Shavarani"
__email__ = "sshavara@sfu.ca"
__status__ = "Production"
