__package__ = "translate.models.aspects"
__all__ = ["ae_utils", "aspect_extract_main", "extract_vocab", "model", "module", "tester", "trainer"]
__author__ = "Hassan S. Shavarani"
__copyright__ = "Copyright 2019, SFUTranslate Project"
__credits__ = ["Hassan S. Shavarani"]
__license__ = "GNU GPL 3"
__version__ = "1.0"
__maintainer__ = "Hassan S. Shavarani"
__email__ = "sshavara@sfu.ca"
__status__ = "Production"
