__package__ = "translate"
__all__ = ["models", "readers", "scripts", "utils", "configuration", "trainer", "test_trained_model", "extract_common_vocab"]
__author__ = "Hassan S. Shavarani"
__copyright__ = "Copyright 2019, SFUTranslate Project"
__credits__ = ["Hassan S. Shavarani"]
__license__ = "GNU GPL 3"
__version__ = "1.0"
__maintainer__ = "Hassan S. Shavarani"
__email__ = "sshavara@sfu.ca"
__status__ = "Production"
